### ISSUE TITLE
node-bbs-signatures installation fails on windows

### ISSUE THREAD

**Issue by Veerendra-b** [mattrglobal/node-bbs-signatures#176]
Hi Team,
We see below error while installing node-bbs-signatures in windows.. Looks like there is no tarball for windows (node-v83-win32-x64.tar.gz) at the location  https://github.com/mattrglobal/node-bbs-signatures/releases/

Is there a plan to release a tarball for windows or is there an alternate way to make it work on windows?

------> Logs<-------
node-pre-gyp ERR! cwd C:\UserSpace\Sources\src\lib\node_modules\@mattrglobal\node-bbs-signatures
node-pre-gyp ERR! node -v v14.17.5
node-pre-gyp ERR! node-pre-gyp -v v0.17.0
node-pre-gyp ERR! not ok
**404 status code downloading tarball https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.12.0/node-v83-win32-x64.tar.gz**
npm WARN libagent@1.0.0 No repository field.
npm WARN libagent@1.0.0 No license field.
npm ERR! code ELIFECYCLE

**Comment by tplooker** [comment]
Hi @Veerendra-b thanks for raising, appears there is an issue with binary publishing for windows based version in our GH action, I will look into this and get back to you

**Comment by sloops77** [comment]
@tplooker any update? Our devs are using node-bbs on either osx, linux & win32. v0.11 doesnt exist for osx and >v0.11 doesnt work for win32. we are properly stuck

**Comment by tplooker** [comment]
@sloops77 what version of NodeJS are you running?

**Comment by Eicoon** [comment]
Same issue here
`npm ERR! response status 404 Not Found on https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.13.0/node-v93-win32-x64.tar.gz`

Using Node v16.15.0

**Comment by Sean-Snow** [comment]
> 

+1

**Comment by keydon** [comment]
let me join the party
```
node-pre-gyp ERR! System Linux 5.10.102.1-microsoft-standard-WSL2
node-pre-gyp ERR! cwd /workspaces/crypto/node_modules/@mattrglobal/node-bbs-signatures
node-pre-gyp ERR! node -v v18.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.17.0
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.13.0/node-v108-linux-x64.tar.gz"
```

**Comment by AlexMesser** [comment]
same issue on Mac:

```
node-pre-gyp http GET https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.11.0/node-v93-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.11.0/node-v93-darwin-x64.tar.gz
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.11.0/node-v93-darwin-x64.tar.gz
```

**Comment by sloops77** [comment]
Hey @tplooker
i've overlooked this issue for while. 

We would love to start using bbs sigs but for that to happen we need a lot more build versions that are being built and released. From viewing here i can see that the following platforms are missing: https://github.com/mattrglobal/node-bbs-signatures/releases

for v0.11 which is a dependency of @transmute/did-key and @decentralized-identity/ion-tools. Missing are
- v93 for all platforms (node 16 - which is LTS)

for > v.0.11 which we can hardcode the resolution to to fix the v93 problems. Missing are:
- win32-x64 
- linux-arm64. (The latter is needed for people using docker on newer macs or an arm linux on the aws, etc)

Im happy to help out if you can give me some pointers

**Comment by tplooker** [comment]
Hi all, the latest release supports both Node v14 and v16 on linux and macos (including arm based architecture) the problem with windows based releases is due to an unresolved issue in [Neon](https://github.com/neon-bindings/neon/issues/822). We are exploring future possible releases of the library that moves away from neon because it is now an unmaintained project.

**Comment by tplooker** [comment]
> same issue on Mac:
> 
> ```
> node-pre-gyp http GET https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.11.0/node-v93-darwin-x64.tar.gz
> node-pre-gyp http 404 https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.11.0/node-v93-darwin-x64.tar.gz
> node-pre-gyp ERR! install error 
> node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.11.0/node-v93-darwin-x64.tar.gz
> ```

@AlexMesser arm based binaries were added in [v0.15.0](https://github.com/mattrglobal/node-bbs-signatures/releases)

**Comment by tplooker** [comment]
Closing this issue as it appears resolved in the latest release, reopen if required.

**Comment by nklomp** [comment]
Not sure if that assessment is correct. The original ticket was about Windows builds.

With the latest release on Node16 on Windows you still get:
```node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.15.0/node-v93-win32-x64.tar.gz```

Which makes sense as the binaries for Windows indeed aren't present.

So it seems the neon migration is needed for Windows builds
